sudo: required
language: node_js
node_js:
- node
services:
- docker
script: ci-scripts/test && ci-scripts/build && ci-scripts/deploy
notifications:
  slack:
    secure: QcAQAbflDtwZ8cIF19AN+zXZkxRlxYyKNLRkw6F8NuHhS+NK2k4Ohq/SIOZoUYgjKq59sAwSqa9iIfJDEHrFXBKircWc+DFJ6UbYS3cGb96/08BSmmW6tG+JI5xPskHL/zGVWG1rP2p4GPUop/hDq99G6qBV+k2lXVdbGXo/ZA87PxcW9WgZD2rcQMAzRj3UdyatWdcsCn7xRM7ZZgxBonSrvfD4CWDseZSrN0xnHw8tbeEHY7g42mnWqnjL0vIQIRtn/IEgiijiM6xkCDKOwtWJ2py7Vn/MtYoOKVaOVByjO9cQy2xxTA85AbSKc1qwM64dQHcFcKSFdpYqkuS2TQoLZBbwiOIVWbbUEwRzhiNLc9LG7K5qdPe2mmDfmjWVpFyvwcAUHB1vvUs3fF9ORfgkC+oHQcdD46goyNBaIwWA1l4iAUV9T1TLOBw0OWINLbcVJAe+1q/V0zWHDQytrs5Tkn/Es2ejsvxb+GL/78mEwEmE7KmnMFdbH9y2et7DQO1EbmvJkNa3VcahrW2JVHzw2c8XMSfHEXJ82/cMmvR1gSwGVxOSSZmNkxLf2R+TpXzVF+34XgWlyKUYyACv6ij8gH2pVAnOtZipBua6ui36Faftdrg+RP/8CyThOCgrVhdk6++6dCIflGSPN/CyBGURYK69a5/lEoKaRgZAiDY=
